/*
 * This file is generated by jOOQ.
 */
package com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IBlogAuthor : Serializable {
    var id: Long?
    var firstName: String?
    var lastName: String?
    var rowVersion: Int?
    var rowCreatedBy: String?
    var rowCreatedOn: LocalDateTime?
    var rowUpdatedBy: String?
    var rowUpdatedOn: LocalDateTime?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IBlogAuthor
     */
    fun from(from: IBlogAuthor)

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IBlogAuthor
     */
    fun <E : IBlogAuthor> into(into: E): E
}
