/*
 * This file is generated by jOOQ.
 */
package com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.interfaces


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IPostPostCategory : Serializable {
    var postId: Long?
    var categoryId: Long?

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IPostPostCategory
     */
    fun from(from: IPostPostCategory)

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IPostPostCategory
     */
    fun <E : IPostPostCategory> into(into: E): E
}
