/*
 * This file is generated by jOOQ.
 */
package com.gmurray.tech.blog.infrastructure.jooq.persistence


import com.gmurray.tech.blog.infrastructure.jooq.persistence.sequences.BLOG_AUTHOR_SEQ
import com.gmurray.tech.blog.infrastructure.jooq.persistence.sequences.BLOG_POST_SEQ
import com.gmurray.tech.blog.infrastructure.jooq.persistence.sequences.POST_CATEGORY_SEQ
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.BlogAuthor
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.BlogPost
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.PostCategory
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.PostPostCategory

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Sequence
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TechBlog : SchemaImpl("tech_blog", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>tech_blog</code>
         */
        val TECH_BLOG: TechBlog = TechBlog()
    }

    /**
     * The table <code>tech_blog.blog_author</code>.
     */
    val BLOG_AUTHOR: BlogAuthor get() = BlogAuthor.BLOG_AUTHOR

    /**
     * The table <code>tech_blog.blog_post</code>.
     */
    val BLOG_POST: BlogPost get() = BlogPost.BLOG_POST

    /**
     * The table <code>tech_blog.post_category</code>.
     */
    val POST_CATEGORY: PostCategory get() = PostCategory.POST_CATEGORY

    /**
     * The table <code>tech_blog.post_post_category</code>.
     */
    val POST_POST_CATEGORY: PostPostCategory get() = PostPostCategory.POST_POST_CATEGORY

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getSequences(): List<Sequence<*>> = listOf(
        BLOG_AUTHOR_SEQ,
        BLOG_POST_SEQ,
        POST_CATEGORY_SEQ
    )

    override fun getTables(): List<Table<*>> = listOf(
        BlogAuthor.BLOG_AUTHOR,
        BlogPost.BLOG_POST,
        PostCategory.POST_CATEGORY,
        PostPostCategory.POST_POST_CATEGORY
    )
}
