/*
 * This file is generated by jOOQ.
 */
package com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.daos


import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.PostCategory
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.records.PostCategoryRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl
import org.springframework.stereotype.Repository


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
@Repository
open class PostCategoryDao(configuration: Configuration?) : DAOImpl<PostCategoryRecord, com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory, Long>(PostCategory.POST_CATEGORY, com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory::class.java, configuration) {

    /**
     * Create a new PostCategoryDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetchRange(PostCategory.POST_CATEGORY.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetch(PostCategory.POST_CATEGORY.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory? = fetchOne(PostCategory.POST_CATEGORY.ID, value)

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfName(lowerInclusive: String?, upperInclusive: String?): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetchRange(PostCategory.POST_CATEGORY.NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    fun fetchByName(vararg values: String): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetch(PostCategory.POST_CATEGORY.NAME, *values)

    /**
     * Fetch records that have <code>row_version BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfRowVersion(lowerInclusive: Int?, upperInclusive: Int?): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetchRange(PostCategory.POST_CATEGORY.ROW_VERSION, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>row_version IN (values)</code>
     */
    fun fetchByRowVersion(vararg values: Int): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetch(PostCategory.POST_CATEGORY.ROW_VERSION, *values.toTypedArray())

    /**
     * Fetch records that have <code>row_created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfRowCreatedBy(lowerInclusive: String?, upperInclusive: String?): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetchRange(PostCategory.POST_CATEGORY.ROW_CREATED_BY, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>row_created_by IN (values)</code>
     */
    fun fetchByRowCreatedBy(vararg values: String): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetch(PostCategory.POST_CATEGORY.ROW_CREATED_BY, *values)

    /**
     * Fetch records that have <code>row_created_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfRowCreatedOn(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetchRange(PostCategory.POST_CATEGORY.ROW_CREATED_ON, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>row_created_on IN (values)</code>
     */
    fun fetchByRowCreatedOn(vararg values: LocalDateTime): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetch(PostCategory.POST_CATEGORY.ROW_CREATED_ON, *values)

    /**
     * Fetch records that have <code>row_updated_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfRowUpdatedBy(lowerInclusive: String?, upperInclusive: String?): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetchRange(PostCategory.POST_CATEGORY.ROW_UPDATED_BY, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>row_updated_by IN (values)</code>
     */
    fun fetchByRowUpdatedBy(vararg values: String): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetch(PostCategory.POST_CATEGORY.ROW_UPDATED_BY, *values)

    /**
     * Fetch records that have <code>row_updated_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfRowUpdatedOn(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetchRange(PostCategory.POST_CATEGORY.ROW_UPDATED_ON, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>row_updated_on IN (values)</code>
     */
    fun fetchByRowUpdatedOn(vararg values: LocalDateTime): List<com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.pojos.PostCategory> = fetch(PostCategory.POST_CATEGORY.ROW_UPDATED_ON, *values)
}
