/*
 * This file is generated by jOOQ.
 */
package com.gmurray.tech.blog.infrastructure.jooq.persistence.sequences


import com.gmurray.tech.blog.infrastructure.jooq.persistence.TechBlog

import org.jooq.Sequence
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType



/**
 * The sequence <code>tech_blog.blog_author_seq</code>
 */
val BLOG_AUTHOR_SEQ: Sequence<Long> = Internal.createSequence("blog_author_seq", TechBlog.TECH_BLOG, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null)

/**
 * The sequence <code>tech_blog.blog_post_seq</code>
 */
val BLOG_POST_SEQ: Sequence<Long> = Internal.createSequence("blog_post_seq", TechBlog.TECH_BLOG, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null)

/**
 * The sequence <code>tech_blog.post_category_seq</code>
 */
val POST_CATEGORY_SEQ: Sequence<Long> = Internal.createSequence("post_category_seq", TechBlog.TECH_BLOG, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null)
