version: "3"
##------------------------
# Recall data-transfer Postgres 12 Docker service
# * Postgres service on port 5436 with databases:
#    - demo_tech_blog
#    - demo_tech_blog_test
##-----------------------

services:

  postgres-12:
    container_name: tb_postgres-12
    command: postgres -c 'max_connections=400' -c 'log_statement=all'
    build:
      context: "db-postgres-12"
      dockerfile: "Dockerfile"
    image: "postgres:12"
    ports:
      - "5436:5432"
    volumes:
      - "db-data-tb-postgres-12:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin1234!"
      - "DB_NAME=demo_tech_blog, demo_tech_blog_test"
    networks:
      - postgres

volumes:
  db-data-tb-postgres-12:
    driver: "local"

networks:
  postgres:
    driver: "bridge"