/*
 * This file is generated by jOOQ.
 */
package com.gmurray.tech.blog.infrastructure.jooq.persistence.tables


import com.gmurray.tech.blog.infrastructure.jooq.persistence.TechBlog
import com.gmurray.tech.blog.infrastructure.jooq.persistence.keys.PK_POST_CATEGORY
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.records.PostCategoryRecord

import java.time.LocalDateTime
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PostCategory(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, PostCategoryRecord>?,
    aliased: Table<PostCategoryRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<PostCategoryRecord>(
    alias,
    TechBlog.TECH_BLOG,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>tech_blog.post_category</code>
         */
        val POST_CATEGORY: PostCategory = PostCategory()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PostCategoryRecord> = PostCategoryRecord::class.java

    /**
     * The column <code>tech_blog.post_category.id</code>.
     */
    val ID: TableField<PostCategoryRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>tech_blog.post_category.name</code>.
     */
    val NAME: TableField<PostCategoryRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>tech_blog.post_category.row_version</code>.
     */
    val ROW_VERSION: TableField<PostCategoryRecord, Int?> = createField(DSL.name("row_version"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>tech_blog.post_category.row_created_by</code>.
     */
    val ROW_CREATED_BY: TableField<PostCategoryRecord, String?> = createField(DSL.name("row_created_by"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>tech_blog.post_category.row_created_on</code>.
     */
    val ROW_CREATED_ON: TableField<PostCategoryRecord, LocalDateTime?> = createField(DSL.name("row_created_on"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>tech_blog.post_category.row_updated_by</code>.
     */
    val ROW_UPDATED_BY: TableField<PostCategoryRecord, String?> = createField(DSL.name("row_updated_by"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL::character varying"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>tech_blog.post_category.row_updated_on</code>.
     */
    val ROW_UPDATED_ON: TableField<PostCategoryRecord, LocalDateTime?> = createField(DSL.name("row_updated_on"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<PostCategoryRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<PostCategoryRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>tech_blog.post_category</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>tech_blog.post_category</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>tech_blog.post_category</code> table reference
     */
    constructor(): this(DSL.name("post_category"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, PostCategoryRecord>): this(Internal.createPathAlias(child, key), child, key, POST_CATEGORY, null)
    override fun getSchema(): Schema? = if (aliased()) null else TechBlog.TECH_BLOG
    override fun getIdentity(): Identity<PostCategoryRecord, Long?> = super.getIdentity() as Identity<PostCategoryRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<PostCategoryRecord> = PK_POST_CATEGORY
    override fun getRecordVersion(): TableField<PostCategoryRecord, Int?> = ROW_VERSION
    override fun getRecordTimestamp(): TableField<PostCategoryRecord, LocalDateTime?> = ROW_CREATED_ON
    override fun `as`(alias: String): PostCategory = PostCategory(DSL.name(alias), this)
    override fun `as`(alias: Name): PostCategory = PostCategory(alias, this)
    override fun `as`(alias: Table<*>): PostCategory = PostCategory(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PostCategory = PostCategory(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PostCategory = PostCategory(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PostCategory = PostCategory(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row7<Long?, String?, Int?, String?, LocalDateTime?, String?, LocalDateTime?> = super.fieldsRow() as Row7<Long?, String?, Int?, String?, LocalDateTime?, String?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, String?, Int?, String?, LocalDateTime?, String?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, String?, Int?, String?, LocalDateTime?, String?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
