/*
 * This file is generated by jOOQ.
 */
package com.gmurray.tech.blog.infrastructure.jooq.persistence.keys


import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.BlogAuthor
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.BlogPost
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.PostCategory
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.PostPostCategory
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.records.BlogAuthorRecord
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.records.BlogPostRecord
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.records.PostCategoryRecord
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.records.PostPostCategoryRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val PK_BLOG_AUTHOR: UniqueKey<BlogAuthorRecord> = Internal.createUniqueKey(BlogAuthor.BLOG_AUTHOR, DSL.name("pk_blog_author"), arrayOf(BlogAuthor.BLOG_AUTHOR.ID), true)
val PK_BLOG_POST: UniqueKey<BlogPostRecord> = Internal.createUniqueKey(BlogPost.BLOG_POST, DSL.name("pk_blog_post"), arrayOf(BlogPost.BLOG_POST.ID), true)
val PK_POST_CATEGORY: UniqueKey<PostCategoryRecord> = Internal.createUniqueKey(PostCategory.POST_CATEGORY, DSL.name("pk_post_category"), arrayOf(PostCategory.POST_CATEGORY.ID), true)
val PK_POST_POST_CATEGORY: UniqueKey<PostPostCategoryRecord> = Internal.createUniqueKey(PostPostCategory.POST_POST_CATEGORY, DSL.name("pk_post_post_category"), arrayOf(PostPostCategory.POST_POST_CATEGORY.POST_ID, PostPostCategory.POST_POST_CATEGORY.CATEGORY_ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val BLOG_POST__FK_BLOG_AUTHOR: ForeignKey<BlogPostRecord, BlogAuthorRecord> = Internal.createForeignKey(BlogPost.BLOG_POST, DSL.name("fk_blog_author"), arrayOf(BlogPost.BLOG_POST.AUTHOR_ID), com.gmurray.tech.blog.infrastructure.jooq.persistence.keys.PK_BLOG_AUTHOR, arrayOf(BlogAuthor.BLOG_AUTHOR.ID), true)
val POST_POST_CATEGORY__FK_POST_POST_CATEGORY_CATEGORY_ID: ForeignKey<PostPostCategoryRecord, PostCategoryRecord> = Internal.createForeignKey(PostPostCategory.POST_POST_CATEGORY, DSL.name("fk_post_post_category_category_id"), arrayOf(PostPostCategory.POST_POST_CATEGORY.CATEGORY_ID), com.gmurray.tech.blog.infrastructure.jooq.persistence.keys.PK_POST_CATEGORY, arrayOf(PostCategory.POST_CATEGORY.ID), true)
val POST_POST_CATEGORY__FK_POST_POST_CATEGORY_POST_ID: ForeignKey<PostPostCategoryRecord, BlogPostRecord> = Internal.createForeignKey(PostPostCategory.POST_POST_CATEGORY, DSL.name("fk_post_post_category_post_id"), arrayOf(PostPostCategory.POST_POST_CATEGORY.POST_ID), com.gmurray.tech.blog.infrastructure.jooq.persistence.keys.PK_BLOG_POST, arrayOf(BlogPost.BLOG_POST.ID), true)
