name: Maven Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13  # Use the appropriate PostgreSQL version
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin1234!
          POSTGRES_DB: demo_tech_blog_test
        ports:
          - 5436:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build and Test
        run: mvn -ntp -B -U -Dlogging.level.root=WARN verify