/*
 * This file is generated by jOOQ.
 */
package com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.references


import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.BlogAuthor
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.BlogPost
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.PostCategory
import com.gmurray.tech.blog.infrastructure.jooq.persistence.tables.PostPostCategory



/**
 * The table <code>tech_blog.blog_author</code>.
 */
val BLOG_AUTHOR: BlogAuthor = BlogAuthor.BLOG_AUTHOR

/**
 * The table <code>tech_blog.blog_post</code>.
 */
val BLOG_POST: BlogPost = BlogPost.BLOG_POST

/**
 * The table <code>tech_blog.post_category</code>.
 */
val POST_CATEGORY: PostCategory = PostCategory.POST_CATEGORY

/**
 * The table <code>tech_blog.post_post_category</code>.
 */
val POST_POST_CATEGORY: PostPostCategory = PostPostCategory.POST_POST_CATEGORY
